-- 1. Tablas Maestras (Sin dependencias externas)
CREATE TABLE empresas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_empresa TEXT NOT NULL,
    rut TEXT,
    industria TEXT,
    propietario_id BIGINT
);

CREATE TABLE servicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_servicio TEXT NOT NULL,
    color_etiqueta TEXT
);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol TEXT NOT NULL UNIQUE
);

CREATE TABLE permisos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave_permiso TEXT NOT NULL UNIQUE,
    descripcion TEXT
);

-- 2. Usuarios (Depende de roles)
CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    rol_id BIGINT REFERENCES roles(id),
    estado BOOLEAN DEFAULT TRUE,
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    google_id TEXT
);

-- 3. Solicitudes (Depende de empresas, servicios y usuarios)
CREATE TABLE solicitudes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT,
    empresa TEXT,
    telefono TEXT,
    email TEXT,
    servicio TEXT,
    mensaje TEXT,
    estado TEXT DEFAULT 'pendiente',
    prioridad TEXT DEFAULT 'normal',
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    codigo_ticket TEXT,
    empresa_id BIGINT REFERENCES empresas(id),
    servicio_id BIGINT REFERENCES servicios(id),
    operador_id BIGINT REFERENCES usuarios(id)
);

-- 4. Tablas Intermedias y de Bitácora
CREATE TABLE rol_permisos (
    rol_id BIGINT REFERENCES roles(id),
    permiso_id BIGINT REFERENCES permisos(id),
    PRIMARY KEY (rol_id, permiso_id)
);

CREATE TABLE usuario_permisos (
    usuario_id BIGINT REFERENCES usuarios(id),
    permiso_id BIGINT REFERENCES permisos(id),
    PRIMARY KEY (usuario_id, permiso_id)
);

CREATE TABLE feedback_servicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES solicitudes(id),
    calificacion INT NOT NULL,
    comentario TEXT,
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bitacora_ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES solicitudes(id),
    mensaje_actualizacion TEXT,
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. Trigger para generar el codigo_ticket automáticamente
CREATE OR REPLACE FUNCTION generar_codigo_ticket_func()
RETURNS TRIGGER AS $$
BEGIN
  NEW.codigo_ticket := 'KLIN-' || LPAD(NEW.id::text, 4, '0');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_generar_codigo_ticket
BEFORE INSERT ON solicitudes
FOR EACH ROW
EXECUTE FUNCTION generar_codigo_ticket_func();

-- 6. Inserción de Roles y Permisos iniciales
INSERT INTO roles (nombre_rol) VALUES ('Administrador'), ('Supervisor'), ('Operador');

INSERT INTO permisos (clave_permiso, descripcion) VALUES 
('dashboard', 'ACCESO AL DASHBOARD'),
('solicitudes', 'ACCESO A SOLICITUDES'),
('clientes', 'ACCESO A CLIENTES'),
('reportes', 'ACCESO A REPORTES'),
('configuracion', 'ACCESO A CONFIGURAR'),
('cambiar_prioridad', 'CAMBIAR PRIORIDAD'),
('cambiar_estado', 'CAMBIAR ESTADO'),
('modificar_permisos', 'MODIFICAR PERMISOS USUARIOS'),
('descargar_reportes', 'DESCARGAR REPORTES'),
('ver_cartera', 'Ver Cartera de Clientes'),
('edit_ticket', 'Editar Estados de Tickets'),
('admin_users', 'Gestionar Usuarios y Configuración');



-- Registro manual de clau.
INSERT INTO usuarios (nombre, email, password_hash, rol_id, estado, google_id)
VALUES (
    'Claudia Klinger', 
    'claudia.klinger@klinman.com', 
    'NOPASSWORD_GOOGLE_AUTH', 
    (SELECT id FROM roles WHERE nombre_rol = 'Administrador' LIMIT 1),
    TRUE,
    NULL -- Esto se actualizará cuando ella inicie sesión la primera vez
) ON CONFLICT (email) DO NOTHING;



SELECT * FROM usuarios;